baseURL: "https://iceyictw.github.io/devblog/"
languageCode: "zh-tw"
paginate: 10  # number of elements per page
title: "ICEYIC"
theme: "PaperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
